### ISSUE TITLE
Removing SchemaType Broke Request

### ISSUE THREAD

**Issue by maarek** [riferrei/srclient#19]
Ref #11 #12 

I am not sure if there was a case where the Schema Registry that @alok87 was on was not updated to the latest API but by removing `schemaType`, all Schemas are now assumed to be AVRO and break PROTOBUF requests.

We should revert PR #12 and come to more understandings on a case where `schemaType` is not available on the API.

Confluent Schema Registery API Doc
[https://docs.confluent.io/current/schema-registry/develop/api.html#post--subjects-(string-%20subject)-versions](https://docs.confluent.io/current/schema-registry/develop/api.html#post--subjects-(string-%20subject)-versions)

**Comment by riferrei** [comment]
Hey @maarek I think you're right. I just added you as collaborator of this repo. Could you please make these changes?

Thanks,

-- @riferrei

**Comment by chrisdginn** [comment]
Having added that code, I agree.  Removing schema type means the client only works for Avro.
