### ISSUE TITLE
Retry support

### ISSUE THREAD

**Issue by alok87** [riferrei/srclient#26]
I had to add a retry functionality. This library supports retry then it would be nice.
 
I understand there is a cache already there. But this is needed when 1000 tables schema calls happen together for the first time the process starts. A simple retry is very useful here.

```go
// GetLatestSchemaWithRetry gets the latest schema with some retry on failure
func GetLatestSchemaWithRetry(client *srclient.SchemaRegistryClient,
	topic string, isKey bool, attempts int) (*srclient.Schema, error) {
	for i := 0; ; i++ {
		schema, err := client.GetLatestSchema(topic, isKey)
		if err != nil {
			return schema, nil
		}
		if i >= (attempts - 1) {
			return nil, fmt.Errorf("Failed to get latest schema, err:%v\n", err)
		}
		klog.Warningf("Error fetching latest schema, err:%v\n", err)
		sleepFor := time.Duration((i * 1000) + 1)
		time.Sleep(sleepFor * time.Millisecond)
	}
}
```

**Comment by AtakanColak** [comment]
Regarding a lot of schema calls happening at the same time, we added #33, a semaphore to avoid too many files open error. However I think a retry functionality should not be a part of the library as different users may have different error handling logic. If this and similar utility features are still requested perhaps we could add a util package.

**Comment by riferrei** [comment]
I agree with @AtakanColak that different users may have different error handling logic. Perhaps what we could do is by default having the client not handling retries and the user (technically, a developer) could register a retryLogic optionally. This retryLogic could be an interface where each one provides their own implementation. The rationale for this is that each user may have different error handling logic's such as always sleeping incrementally as shown by @alok87 or perhaps something more elaborated such as exponential backoff.

Given people a way to provide a ad-hoc retry logic is IMHO better than setting this behavior statically in the code. Eventually someone will disagree and request a refactor ¯\_(ツ)_/¯

What y'all think?

**Comment by AtakanColak** [comment]
@riferrei this solution sounds like an error handling callback, but I personally don't think a callback is any different from a function like given above, but a little more complicated for both parties as the user still has to write the function. I would prefer  to leave the library as simple as possible with leaving the error handling completely to the importing package.

**Comment by riferrei** [comment]
Fair enough. I prefer simplicity over completeness as well. I think the key here is making sure that the library doesn't impose any logic that not always developers would like. So letting the caller handle the retries seems like the best of both worlds to me. But always open to be wrong :smiling_face_with_three_hearts:

**Comment by alok87** [comment]
I ended up using https://github.com/avast/retry-go which has support for various use cases with crashloop, random etc...

**Comment by AtakanColak** [comment]
Closing issue as necessary discussion is done, and author also provided two solutions.
