### ISSUE TITLE
Default initialisation of SchemaRegistryClient does not support Protobuf

### ISSUE THREAD

**Issue by tomarrell** [riferrei/srclient#30]
There is a hard coded configuration value `codecCreationEnabled`, which is used [here](https://github.com/riferrei/srclient/blob/master/schemaRegistryClient.go#L342) in order determine whether or not a new Avro codec should be created.

As this value is hard coded to `true`, ~and there is no way to override it~, the library as it stands does not support Protobuf.

**Comment by tomarrell** [comment]
Ah, just found the `CodecCreationEnabled` method. This is a bit obscure that you need to configure the client after it has been initialised. The default initialisation also doesn't support Protobuf due to this. 

I would therefore recommend that this is re-evaluated to allow a default SchemaClient support proto.

**Comment by AtakanColak** [comment]
@tomarrell I'd like to hear your thoughts about #36
