### ISSUE TITLE
Allow arbitrary subject names

### ISSUE THREAD

**Issue by Navgeet** [riferrei/srclient#4]
It would be nice if the library allowed using arbitrary subject names instead of appending `-key` or `-value`.

**Comment by mntlty** [comment]
This is the biggest blocker for me to use this library, as our team already has a convention on subject names that does not include these values. What is the context for this convention on subject names?

**Comment by AtakanColak** [comment]
It's related to Confluent Platform afaik. I want to solve this issue but can't really think of a way to allow it without breaking changes.

**Comment by matrixise** [comment]
Arghhh, I wanted to use this lib, but it's a blocking issue.

**Comment by AtakanColak** [comment]
All right, I'll work on it.

**Comment by arkiaconsulting** [comment]
@riferrei @AtakanColak Hi. I would like to contribute. I have a local branch ready to create schemas with arbitrary names.

**Comment by AtakanColak** [comment]
@arkiaconsulting Hi, thanks for your consideration. Could you create a pull request so we can work from there?

**Comment by arkiaconsulting** [comment]
@AtakanColak I don't have the permission to push a branch

**Comment by AtakanColak** [comment]
@arkiaconsulting You need to fork the project to a repo on your own, push your changes to it and then create pull request at your own repository. See https://opensource.com/article/19/7/create-pull-request-github

**Comment by arkiaconsulting** [comment]
@AtakanColak PR on the way

**Comment by AtakanColak** [comment]
@arkiaconsulting you are right, I created the release so versioning can be used as part of the modules

**Comment by matrixise** [comment]
Nice
