### ISSUE TITLE
Version 0.4 is not resolved by go mod download

### ISSUE THREAD

**Issue by dstendardi** [riferrei/srclient#50]
## Description of the problem

I tried to use version `0.4` published by @AtakanColak. Unfortunately this is what I get when syncing go modules 👍 

```
go: errors parsing go.mod:
/xxx/Worskpace/go.mod:7:2: no matching versions for query "v0.4"
```

## Proposed solution

Create a version 0.4.0 which fits go standard practices.

**Comment by riferrei** [comment]
Done. Sorry about this 🙈
