### ISSUE TITLE
srclient.Schema fields unexported without constructor - makes SchemaRegistryClient unmockable

### ISSUE THREAD

**Issue by ideasculptor** [riferrei/srclient#51]
All members of srclient.Schema are unexported, so it is impossible to populate an instance of srclient.Schema with values.  When implementing a mock SchemaRegistryClient, I want to specify the schema instance that should be returned by GetLatestSchema, but I am unable to without resorting to obnoxious reflection tricks.  

It's all well and good to create an immutable struct, but how about providing a constructor or a builder of some kind so that it is at least possible to create one for testing. I am reluctant to use the provided MockSchemaRegistryClient because that mock has far too much logic in it, which might include bugs of its own.  A mock should be super simple and just allow for the injection of return values for a given method call. And it is easy enough to create such a mock, except that the return value I need to inject cannot be populated because it is immutable and lacks a constructor.

This kind of thing shouldn't be necessary, and wouldn't be if there was a constructor function
```
	suite.schema = &srclient.Schema{}
	SetUnexportedField(reflect.ValueOf(suite.schema).Elem().FieldByName("id"), 1)
	SetUnexportedField(reflect.ValueOf(suite.schema).Elem().FieldByName("schema"), "MyDomainEvent")
	SetUnexportedField(reflect.ValueOf(suite.schema).Elem().FieldByName("version"), 1)

	suite.srclient = new(MockRegistryClient)
	suite.srclient.On("GetLatestSchema", "MyDomainEvent", false).Return(suite.schema, nil)
```

**Comment by AtakanColak** [comment]
Would this function satisfy your testing requirements?

```go
func NewSchema(id int, schema string, version int, references []Reference, codec *goavro.Codec) Schema
```

**Comment by ideasculptor** [comment]
Most definitely.  That's exactly what I'm looking for

**Comment by AbdulRahmanAlHamali** [comment]
Hello, I notice that this hasn't made it yet to the official release. Any reason for that?

**Comment by AtakanColak** [comment]
Just an oversight, thank you, v0.5 is out now.
