### ISSUE TITLE
MockSchemaRegistryClient.GetLatestSchema() panics when called with an an inexistent subject

### ISSUE THREAD

**Issue by topliceanu** [riferrei/srclient#64]
This is where the panic happens: https://github.com/riferrei/srclient/blob/v0.4.0/mockSchemaRegistryClient.go#L110 

### How to reproduce?
```go
client := srclient.CreateMockSchemaRegistryClient(<some-mock-url>)
schema, err := client.GetLatestSchema("<some-inexistent-schema-subject>")
```

**Comment by AtakanColak** [comment]
Good catch, any PRs welcome.

**Comment by topliceanu** [comment]
Done @AtakanColak. See https://github.com/riferrei/srclient/pull/67
