### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by mostafa** [riferrei/srclient#78]
Hey @riferrei,

Thanks for your awesome library. I'm using it in my project [xk6-kafka](https://github.com/mostafa/xk6-kafka/pull/52),  as you already know. I thought it would be a good idea to introduce some metrics into the library functions, so the usages, network traffic and a few different things can be measured. If I can find some time, I'll probably do that.

Also, I'd very happy to have your feedback on this. :pray:

**Comment by riferrei** [comment]
I'm a huge fan of metrics. Let's collaborate on that. How are you thinking about exporting then?

**Comment by mostafa** [comment]
Then let's do it!

In terms of metrics, xk6-kafka needs to eventually expprt the metrics to k6. The kafka-go package does a good job of exporting [stats](https://github.com/segmentio/kafka-go/blob/main/stats.go), which BTW I think would be the way to go, and I [redefined and registered](https://github.com/mostafa/xk6-kafka/blob/main/stats.go) them in the k6 metrics registery. Then I exported them  in the [producer](https://github.com/mostafa/xk6-kafka/blob/0f4a3b8e00bc7c4fd81fa566724ef7460d4cfcc0/producer.go#L166) and [consumer](https://github.com/mostafa/xk6-kafka/blob/0f4a3b8e00bc7c4fd81fa566724ef7460d4cfcc0/consumer.go#L143).

**Comment by AtakanColak** [comment]
Do you mean providing metrics for srclient, or metrics for schema registry via srclient?

**Comment by mostafa** [comment]
@AtakanColak
I mean metrics for srclient. For example, a succeeded/failed dial to the endpoint, or the same when getting or creating a schema. If you look at the [linked issue](https://github.com/mostafa/xk6-kafka/issues/23) on my project, you'll see what I meant.

**Comment by mostafa** [comment]
@AtakanColak Would be very happy to review the PR.

**Comment by mostafa** [comment]
@AtakanColak Have you found any time to spend on this?

**Comment by AtakanColak** [comment]
@mostafa Sadly not, I had prioritised #86. I don't think I'll have the time for it in short term, but will work on it in the future if no one has done so.

**Comment by mostafa** [comment]
@AtakanColak No worries! I am also working on refactoring my extension and will see if I can do it after I've finished with the refactorings.

**Comment by AtakanColak** [comment]
@mostafa I've started this and I think below are the metrics we'll be able to provide, does that make sense to you?;

```go
type SchemaRegistryClientMetrics struct {
	Timestamp                  time.Time
	CurrentSchemaCount         uint32
	DeletedSchemaCount         uint32
	CreatedAvroSchemaCount     uint32
	CreatedJSONSchemaCount     uint32
	CreatedProtobufSchemaCount uint32
	TotalHTTPRequestsCount     uint32
}

**Comment by mostafa** [comment]
@AtakanColak
These are good as the baseline metrics. However, this is an HTTP client, and it would be nice to export more metrics, if possible, like [the metrics](https://k6.io/docs/using-k6/metrics/#http-specific-built-in-metrics) k6 exports, which are available [here](https://github.com/grafana/k6/tree/master/metrics).

**Comment by AtakanColak** [comment]
If so then I'd like to leave this work to you.

**Comment by AtakanColak** [comment]
Dear @mostafa , are there any updates on this? If not, then I'm inclined to close this issue.

**Comment by AtakanColak** [comment]
Dear @mostafa , are there any updates on this? If not, then I'm inclined to close this issue.

**Comment by mostafa** [comment]
@AtakanColak 

No updates from my side. Please close it. I'll re-open it when I have time to develop it.
