### ISSUE TITLE
Missing field in GetSchema

### ISSUE THREAD

**Issue by lotus-x** [riferrei/srclient#79]
Hi,

I think `References` field must be included when constructing the `Schema` which is fetched using a schema ID

https://github.com/riferrei/srclient/blob/master/schemaRegistryClient.go#L226

Also I checked with the confluent's schema registry, and it does return the references for the request `/schemas/ids/%s`

**Comment by AtakanColak** [comment]
This is a trivial addition, but I want to combine this release alongside a test suite on Github Actions as I don't have a way of testing it. If someone can verify there will be no bugs for when there are no references, please let me know.

**Comment by AtakanColak** [comment]
Resolved in #89
