### ISSUE TITLE
GetSchema() call does not return schema references as part of the return Schema

### ISSUE THREAD

**Issue by mdpaquin** [riferrei/srclient#87]
While it works fine when fetching a Schema by Subject/Version pair, fetching a Schema by ID does not currently return the linked references. I have PR ready with the fix.

**Comment by AtakanColak** [comment]
Hi, thank you for your contribution, I'm unable to see the PR, could you create a new pull request?

**Comment by AtakanColak** [comment]
You don't need to push your branch to this repository to open a PR to this repository.

**Comment by mdpaquin** [comment]
@AtakanColak sorry, did everything locally, did not initially bother forking. Here is the PR:

https://github.com/riferrei/srclient/pull/89

**Comment by AtakanColak** [comment]
Closed as PR is approved
