### ISSUE TITLE
CreateMockSchemaRegistryClient gives no codec

### ISSUE THREAD

**Issue by survivorbat** [riferrei/srclient#92]
Hey there, 

Loving this library so far, really like that you put thought in using interfaces and mocks, can't express how happy I am that you added those.

One thing I'm struggling with though is that in the following example Codec() is nil.
<img width="970" alt="image" src="https://user-images.githubusercontent.com/32467485/192459562-105119a0-5a65-43a3-b09c-98c8b54a3f65.png">

<img width="736" alt="image" src="https://user-images.githubusercontent.com/32467485/192459426-9a8ce300-8229-43f1-8930-3b5dd977b606.png">

I'm expecting to be able to unit-test the example code, but the Codec is never set or supplied. Am I missing something obvious? Or am I meant to exclude the codec stuff for testing purposes only? I hope not.

Yours sincerely, 

Alex

**Comment by survivorbat** [comment]
I made #94 to take care of both this issue and another one concerning GetSchemaVersion not working properly.

**Comment by ahernandez9** [comment]
@riferrei Is there any plan to launch a new version? Like 0.5.5 or 0.6 stable. It'd be nice to be able to use this contribution by @survivorbat in our unit tests without having to use master in our codebase. Thanks! :)

**Comment by AtakanColak** [comment]
Hi, I should launch a new version once #98 is merged.

**Comment by AtakanColak** [comment]
New version has been released, closing this issue
